- hosts: localhost
  become: false
  tasks:
  - name: Install packages
    become: true
    apt:
      name: ['htop', 'neovim', 'net-tools', 'nfs-common', 'vlc-bin', 'tmux', 'cmake', 'curl']

  - name: Copy properties
    copy: src={{ item.src }} dest={{ item.dest }}
    with_items:
      - { src: 'templates/.vimrc', dest: '~/.vimrc' }
      - { src: 'templates/init.vim', dest: '~/.config/nvim/init.vim' }

  - name: Install vim plugins
    shell: nvim +PluginInstall +qall --headless

  - name: Install oz-my-zsh
    include_tasks: "tasks/oh-my-zsh.yml"

  - git:
      repo: 'https://gitlab.com/interception/linux/plugins/caps2esc'
      dest: '~/src/caps2esc'
