- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    apt: name={{item}}
    with_items: 
        - htop
        - neovim
  - name: Install vim plugins
    shell: nvim +PluginInstall +qall --headless
