- hosts: localhost
  become: false
  tasks:
  - name: Install packages
    become: true
    apt:
      name: ['htop', 'neovim']

  - name: Copy properties
    copy: src={{ item.src }} dest={{ item.dest }}
    with_items:
      - { src: 'templates/.vimrc', dest: '~/.vimrc' }
      - { src: 'templates/init.vim', dest: '~/.config/nvim/init.vim' }

  - name: Install vim plugins
    shell: nvim +PluginInstall +qall --headless
