- hosts: localhost
  become: false
  tasks:
  - name: Install packages
    become: true
    apt:
      name: ['htop', 'neovim']

  - name: Copy templates
    copy: src=templates/.vimrc dest=~/
    copy: src=templates/init.vim dest=~/

  - name: Install vim plugins
    shell: nvim +PluginInstall +qall --headless
